language: ruby
sudo: required
services:
    - docker
#before_install:
#    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
    - docker build -t veggerby/rubik-test .
    - docker run veggerby/rubik-test dotnet test